### ISSUE TITLE
Per-part Uncertainty

### ISSUE THREAD

**Issue by GloryyrolG** [saidwivedi/POCO#2]
Hi @saidwivedi et al.,

Thx for ur work. may i ask if the code/function of per-part uncertainty is currently available? thx & best,

**Comment by saidwivedi** [comment]
Thank you for your interest in our work. POCO, by design, estimates per-part uncertainty (see [here](https://github.com/saidwivedi/POCO/blob/5e2d085f399297184fd8d66588db02e3a59a5108/pocolib/models/head/poco_head.py#L84)). 

We observe that training with per-part uncertainty helps in faster convergence. However, since most HPS methods are trained with real images with pseudo-GT annotations, the annotations are not very accurate (especially for hands and feet), hence the uncertainty estimation for these parts are also not accurate. Hence, we convert per-part uncertainty to scalar body uncertainty (see [here](https://github.com/saidwivedi/POCO/blob/5e2d085f399297184fd8d66588db02e3a59a5108/pocolib/utils/poco_utils.py#L50)) for practical use in downstream tasks.
