### ISSUE TITLE
Question Regarding the Normalizing Flow Equation

### ISSUE THREAD

**Issue by JasonWUCHI** [saidwivedi/POCO#5]
Dear author,

I am trying to understand the equation 4 in the paper, could you help me to clarify some point?

1. Should it be $\bar{\theta}=f_\phi(z)$ instead of $\bar{\theta}=f_\phi^{-1}(z)$
2. How do you deal with the $f_{\phi}^{-1}$ term when you calculate from line 2 to line 3?

Thank you in advance!

**Comment by saidwivedi** [comment]
Thank you interest in our paper :)

1. $`\mathcal{f}_{\phi}`$ is the normalizing flow network which transforms a simple distribution $`z`$ to . Since the network is invertible $`\mathcal{f}_{\phi}^{-1}`$ and we are interested to model the error $`\bar{\theta}`$, hence $`\bar{\theta} = \mathcal{f}_{\phi}^{-1}(z)`$
2. I not sure if I understood the question fully. We replaced $`\mathcal{f}_{\phi}^{-1}(\bar{\theta_{g}})`$ with $`(\theta_{g} - \theta)/\sigma`$ and omitted for simplicity.

This formulation is adapted from [RLE, ICCV 2021](https://arxiv.org/abs/2107.11291) which defined residual log-likelihood. You can refer to the original paper if it helps.
